version: '3.1'
services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=cloud
    ports:
      - '5432:5432'

  app:
    image: cloudimage
    container_name: backend
    ports:
      - '8080:8080'
    depends_on:
      - db



